# Generated by Django 3.2.8 on 2021-11-02 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20211102_0227'),
        ('main_app', '0002_profile'),
    ]

    operations = [
    ]
