# Generated by Django 3.2.8 on 2021-11-03 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_merge_0002_auto_20211102_0227_0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='for_sale',
        ),
    ]
